Add fake network connection info to fix app compatibility issue
projectceladon/vendor-intel-utils pull request #1191
Opened 2021-09-15 08:08 UTC by aiswaryacyriac

Some apps cannot work on ethernet network environment. So we create
fake Wifi connection in ConnectivityManager and WifiManager to fix it.

Signed-off-by: Aiswarya Cyriac <aiswarya.cyriac@intel.com>

2021-10-05 10:19 UTC, balajim001 approved these changes
LGTM

2021-10-05 10:23 UTC, balajim001 approved these changes
LGTM

2021-10-06 05:48 UTC, JeevakaPrabu approved these changes

2021-10-06 05:48 UTC, JeevakaPrabu requested changes
Please raise it for stable branch

2023-08-10 16:54 UTC, closed without merging