enabling long press on the touch screen
projectceladon/vendor-intel-utils pull request #1245
Opened 2021-11-02 04:41 UTC by RajaniRanjan

enabling long press touch features to take video in wechat app

Tracked-On:OAM-99821
Signed-off-by: Rajani Ranjan <rajani.ranjan@intel.com>

2021-11-02 04:48 UTC, balajim001 approved these changes
LGTM

2021-11-02 08:14 UTC, JeevakaPrabu requested changes
please address indentation issues

2021-11-08 04:07 UTC, JeevakaPrabu approved these changes

2021-11-08 09:33 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/63

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2021-11-08 10:53 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-premerge/builds/66

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2021-11-08 15:03 UTC, merged

2021-11-08 15:03 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Ranjan, Rajani" <rajani.ranjan@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_rmr0_stable-mergerequest/builds/40