new fixes for orientation and WA for focus
projectceladon/vendor-intel-utils pull request #1266
Opened 2021-11-15 12:12 UTC by gkdeepa

2021-11-25 06:21 UTC, xihua-chen approved these changes

2021-11-25 06:50 UTC, shivasku82 approved these changes

2021-11-25 06:58 UTC, swaroopbalan approved these changes

2021-11-25 07:59 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/96

2021-11-25 08:24 UTC, shyjumon-n requested changes
Please follow the comments !

2021-11-25 08:24 UTC, shyjumon-n commented on bsp_diff/caas_cfc/vendor/intel/external/project-celadon/camera-vhal/0001-VHAL-changes-for-orien-w.r.t-facing.patch
> ++#define LOG_TAG "CameraSocketServerThread: Deepa"
I think we shall remove these debug prints ?

2021-11-25 08:24 UTC, shyjumon-n commented on bsp_diff/caas_cfc/vendor/intel/external/project-celadon/camera-vhal/0001-VHAL-changes-for-orien-w.r.t-facing.patch
> ++    ALOGI("%s Deepa camera socket server path is %s", __FUNCTION__, mSocketPath.c_str());
We shall remove these debug prints

2021-11-25 08:43 UTC, shyjumon-n approved these changes
Looks good to me

2021-11-25 13:56 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/97

Done by "Deepa, G K" <g.k.deepa@intel.com>

2021-11-25 16:53 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-CML-R(cml_nuc:caas - userdebug), CIT-CIV-CML-R(cml_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-premerge/builds/82

2021-11-26 05:36 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-premerge/builds/85

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2021-11-26 09:34 UTC, merged

2021-11-26 09:35 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_rmr0_stable-mergerequest/builds/62