Integrate MAY-2022 ASB patches
projectceladon/vendor-intel-utils pull request #1420
Opened 2022-04-29 01:24 UTC by rrsenapati1

Tracked-On: OAM-101831
Signed-off-by: Senapati, Rasmiranjan <rasmiranjan.senapati@intel.com>

2022-04-29 11:53 UTC, SaliniVenate requested changes

2022-04-29 11:53 UTC, SaliniVenate commented on aosp_diff/preliminary/packages/providers/MediaProvider/03_0003-Handle-content-uris-without-id-in-checkUriPermission.patch
> +
This is seen as a already applied patch.
Project ./packages/providers/MediaProvider
        Already applied         01_0001-Handle-content-uris-without-id-in-checkUriPermission.patch
        Applying                02_0002-Restrict-legacy-apps-to-insert-files-to-other-privat.patch
        Already applied         03_0003-Handle-content-uris-without-id-in-checkUriPermission.patch

2022-04-29 11:53 UTC, SaliniVenate commented on aosp_diff/preliminary/system/sepolicy/11_0011-Allow-adbd-to-access-proc-net-tcp-tcp6-udp-udp6-.patch
> +ListeningPortsTest.
This is also already applied.
Project ./system/sepolicy
 Already applied         11_0011-Allow-adbd-to-access-proc-net-tcp-tcp6-udp-udp6-.patch

2022-04-29 11:55 UTC, SaliniVenate commented
@rrsenapati1 , recently an AOSP rebase was done on celadon-S and because of that many patches (apart from 2 commented above) are seen as already applied. Below is the list. Please clean up those patches also.
        Already applied         01_0001-Move-slice-increments-after-completing-header-parsin.patch
        Already applied         06_0006-Better-buffer-overrun-prevention.patch
        Already applied         07_0007-Safetynet-logging-for-b-204445255.patch
        Already applied         08_0008-Prevent-out-of-bounds-read.patch
        Already applied         05_0005-Add-missing-size-check-when-parsing-staged-aliases.patch
        Already applied         06_0006-Controls-Do-not-recreate-intent.patch
        Already applied         01_0001-Fix-Managed-Provisioning-crash-on-OTA.patch
        Already applied         01_0001-Rephrase-dialog-message-of-clear-storage-dialog-for-.patch
        Already applied         02_0002-Add-non-system-overlay-flag-to-InstallCaCertificateW.patch
        Already applied         03_0003-Import-translations.-DO-NOT-MERGE-ANYWHERE.patch
        Already applied         01_0001-Handle-content-uris-without-id-in-checkUriPermission.patch
        Already applied         03_0003-Handle-content-uris-without-id-in-checkUriPermission.patch
        Already applied         03_0003-security-Use-After-Free-in-btm_sec_-dis-connected.patch
        Already applied         04_0004-Reset-the-IRK-after-all-devices-are-unpaired.patch
        Already applied         01_0001-Tag-mismatch-in-NFA_SendRawFrame.patch
        Already applied         11_0011-Allow-adbd-to-access-proc-net-tcp-tcp6-udp-udp6-.patch
        Already applied         01_0001-Revert-Revert-Add-automatic-default-value-for-char-t.patch
        Already applied         02_0002-Fix-sc-dev-plus-aosp-builds.patch
        Already applied         0002-Set-the-primary-display-as-internal-display-for-AOSP.patch

2022-04-30 17:38 UTC, SaliniVenate approved these changes
LGTM

2022-05-02 03:18 UTC, shyjumon-n approved these changes
Integrating Google security patches.
LGTM

2022-05-02 04:15 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4184

2022-05-02 04:21 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4186

2022-05-02 07:44 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4189

Done by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com>

2022-05-02 09:54 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2352

Done by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com>

2022-05-02 12:42 UTC, merged

2022-05-02 12:43 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2813