Integrate MAY-2022 ASB patches
projectceladon/vendor-intel-utils pull request #1421
Opened 2022-04-29 02:30 UTC by rrsenapati1

Tracked-On: OAM-101830
Signed-off-by: Senapati, Rasmiranjan <rasmiranjan.senapati@intel.com>

2022-04-29 11:40 UTC, SaliniVenate requested changes

2022-04-29 11:40 UTC, SaliniVenate commented on aosp_diff/preliminary/packages/services/Telecomm/01_0001-Handle-null-bindings-returned-from-ConnectionService-.patch
> +---
Please cross-check if this patch is already present as a part of previous tag. If yes please remove this patch and update the commit id details in the excel sheet you maintain.
I can see it as already applied in your EB stdio logs.
Project ./packages/providers/MediaProvider
                Already applied         04_0004-Avoid-apps-to-get-global-access-with-table-uri.patch

2022-04-29 11:40 UTC, SaliniVenate commented on aosp_diff/preliminary/system/sepolicy/10_0010-0001-Allow-adbd-to-access-proc-net-tcp-tcp6-udp-udp6-.patch
> + 2 files changed, 6 insertions(+)
This is also an already applied patch. Please cross-check and remove.
Project ./system/sepolicy
             Already applied         10_0010-0001-Allow-adbd-to-access-proc-net-tcp-tcp6-udp-udp6-.patch

Also the naming convention is wrong

2022-04-30 17:31 UTC, SaliniVenate approved these changes
LGTM

2022-05-02 03:10 UTC, shyjumon-n approved these changes
Google security patch integration.
LGTM

2022-05-02 04:16 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/336

2022-05-02 04:21 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/337

2022-05-02 10:30 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/338

Done by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com>

2022-05-02 12:17 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-premerge/builds/223

Done by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com>

2022-05-02 16:25 UTC, merged

2022-05-02 16:25 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_rmr0_stable-mergerequest/builds/161