Integrate JULY-2022 ASB patches to R- stable branch
projectceladon/vendor-intel-utils pull request #1487
Opened 2022-06-29 20:20 UTC by rrsenapati1

Tracked-On: OAM-102661
Signed-off-by: Senapati, Rasmiranjan <rasmiranjan.senapati@intel.com>

2022-06-30 16:48 UTC, shyjumon-n approved these changes
LGTM

2022-07-01 06:07 UTC, tanujtekriwal requested changes

2022-07-01 06:07 UTC, tanujtekriwal commented on aosp_diff/preliminary/libcore/02_0002-Reject-non-ASCII-hostnames-and-SANs-.patch
> +From be231aa384e6ffb2807af24d8b9d9919394a6c8a Mon Sep 17 00:00:00 2001
please remove this patch. Its already there.

2022-07-01 06:33 UTC, tanujtekriwal approved these changes
LGTM

2022-07-01 06:43 UTC, tanujtekriwal approved these changes
LGTM

2022-07-01 07:16 UTC, shyjumon-n approved these changes
Google security patch integration. 
LGTM

2022-07-01 12:46 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/385

Done by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com>

2022-07-01 20:55 UTC, merged

2022-07-01 20:56 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Senapati, Rasmiranjan" <rasmiranjan.senapati@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_rmr0_stable-mergerequest/builds/186