avx2 implementation for memset.
projectceladon/vendor-intel-utils pull request #1580
Opened 2022-09-01 06:49 UTC by amritaintel

This patch includes handwritten avx2
assembly for memset 64-bit. Uses
non-temporal stores for very large sizes.
Also includes dynamic dispatch for APIs
having multiple implementations.

Convincing benchmark improvements for sizes above 512 bytes, and
although the slight regression for small sizes is unfortunate, it's
probably small enough to be okay?

Tracked-On: OAM-103728
Signed-off-by: ahs <amrita.h.s@intel.com>

2023-01-24 07:54 UTC, vinaykompella requested changes

2023-01-24 07:54 UTC, vinaykompella commented on aosp_diff/preliminary/bionic/0012-avx2-implementation-for-memset-api.patch
> ++        vpbroadcastb %xmm0, %ymm0
alignment

2023-01-24 07:54 UTC, vinaykompella commented on aosp_diff/preliminary/bionic/0012-avx2-implementation-for-memset-api.patch
> +
Please add some results

2023-01-24 07:54 UTC, vinaykompella commented on aosp_diff/preliminary/bionic/0012-avx2-implementation-for-memset-api.patch
> ++Copyright (c) 2014, Intel Corporation
Update the latest copyright message

2023-01-24 09:59 UTC, vinaykompella approved these changes
LGTM

2023-01-25 06:34 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/273

2023-01-25 06:37 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/274

2023-01-25 08:01 UTC, shyjumon-n approved these changes
LGTM

2023-01-25 10:19 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/275

Done by "H S, Amrita" <amrita.h.s@intel.com>

2023-01-25 10:50 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-premerge/builds/170

Done by "H S, Amrita" <amrita.h.s@intel.com>

2023-01-25 13:11 UTC, merged

2023-01-25 13:12 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "H S, Amrita" <amrita.h.s@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/130