Fix drawing delay issue in cases of resize and rotation for SRIOV
projectceladon/vendor-intel-utils pull request #1616
Opened 2022-09-22 09:27 UTC by lyintel

gd_egl_draw does not flush anything when draw_submitted=false, this inludes the cases of resize and rotation, so add one time flush to fix it.

Tracked-On: OAM-104047
Signed-off-by: Lu Yang A <yang.a.lu@intel.com>

2022-09-22 09:30 UTC, lyintel commented
We have tried another fix to revert  "ui/gtk: skip any extra draw of same guest scanout blob res", commit 55f4b767f64ee0fec397c7ceebfea1473b725963, but it will cause QEMU crash after rotation. So, we choose to use current commit to fix the issue.

2022-09-23 09:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4506

2022-09-23 09:38 UTC, swaroopbalan approved these changes

2022-09-23 12:35 UTC, JeevakaPrabu requested changes
fix the typo "inludes -> includes "

2022-09-26 05:22 UTC, JeevakaPrabu approved these changes

2022-09-26 08:25 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4508

Done by "Lu, Yang A" <yang.a.lu@intel.com>

2022-09-26 12:13 UTC, merged

2022-09-26 12:13 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Lu, Yang A" <yang.a.lu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/3002