rebasing bsp_diff patches for kernel_v-5.4.224
projectceladon/vendor-intel-utils pull request #1692
Opened 2022-12-05 14:18 UTC by rajucm2007

rebasing bsp_diff patches for kernel version-5.4.224

Tracked-On: OAM-105153
Signed-off-by: rajucm <raju.mallikarjun.chegaraddi@intel.com>

2022-12-05 14:55 UTC, JeevakaPrabu requested changes
Any reason behind virtio support removal?

Changes to iwl header file require update in device/intel/common file too.

2022-12-05 23:57 UTC, kaushlen approved these changes

2022-12-06 05:25 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/428

2022-12-06 07:02 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/429

2022-12-06 09:56 UTC, balajim001 approved these changes
LGTM

2022-12-06 11:05 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/430

2022-12-06 12:01 UTC, rajucm2007 commented
> 



> Any reason behind virtio support removal?
> 
> Changes to iwl header file require update in device/intel/common file too.

1) vendor/intel/common - changes pushed  - Please review
    https://github.com/projectceladon/device-intel-common/pull/143
2)  Diff patch rebase summary 
0003-Add-AB24-and-AR24-support-for-virtio-on-Android.patch - removed (support comes in base version)
12_0012-x86-e820-fix-the-function-type-for-e820__mapped_all.patch - removed (causes CFI error must remove)

0023-iwl7000-Vendor-command-support-in-iwl7000-driver.patch - (api params changes)
27_0027-VIRTIO-Freeze-and-Restore-Implementation.patch - (api params changes)

2022-12-07 04:58 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/431

2022-12-07 10:37 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-preintegration/builds/432

Done by "Joshi, Shweta" <shweta.joshi@intel.com>

2022-12-08 05:21 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_rmr0_stable-premerge/builds/309

Done by "Joshi, Shweta" <shweta.joshi@intel.com>

2022-12-08 19:07 UTC, merged

2022-12-08 19:08 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Joshi, Shweta" <shweta.joshi@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_rmr0_stable-mergerequest/builds/211