Bluetooth: btintel: Fix bdaddress with garbage
projectceladon/vendor-intel-utils pull request #1710
Opened 2022-12-28 14:52 UTC by prashanth-intel

Intel Read Verision(TLV) data is parsed into a local structure variable and it contains a field for bd address. Bd address is returned only in bootloader mode and hence bd address in TLV structure needs to be validated only if controller is present in boot loader mode.

Signed-off-by: Kothapeta, BikshapathiX <bikshapathix.kothapeta@intel.com>

2022-12-29 10:18 UTC, sysopenci commented
Expected syntax:
    Commit message one-line summary

      Extra paragraphs can be added here.

      Longer description that explains the problem / solution
      or whatever that needs to be said

      It can contain
        multiple lines
        multiple paragraphs
        blank lines
        references

      But each paragraph must be followed by a blank line

      However, you need to keep the 'Tracked-On', 'Change-Id',
      'Signed-off-by', ..., fields in the **lastest** paragraph of
      the commit message.

      Change-Id: I9e58f79c7faf7f0edb9792e8b5322ab161331141
      Tracked-On: https://jira.server.ext/browse/PROJECTA-123
      Signed-off-by: Developer Name <developer.name@intel.com>

2023-01-13 15:52 UTC, sysopenci commented
Expected syntax:
    Commit message one-line summary

      Extra paragraphs can be added here.

      Longer description that explains the problem / solution
      or whatever that needs to be said

      It can contain
        multiple lines
        multiple paragraphs
        blank lines
        references

      But each paragraph must be followed by a blank line

      However, you need to keep the 'Tracked-On', 'Change-Id',
      'Signed-off-by', ..., fields in the **lastest** paragraph of
      the commit message.

      Change-Id: I9e58f79c7faf7f0edb9792e8b5322ab161331141
      Tracked-On: https://jira.server.ext/browse/PROJECTA-123
      Signed-off-by: Developer Name <developer.name@intel.com>

2023-02-01 07:11 UTC, rajucm2007 approved these changes

2023-02-01 08:08 UTC, JeevakaPrabu requested changes

2023-02-01 08:08 UTC, JeevakaPrabu commented on bsp_diff/common/kernel/lts2020-yocto/0043-Bluetooth-btintel-Fix-bdaddress-comparison-with-garb.patch
> +Intel Read Verision(TLV) data is parsed into a local structure variable
fix the typo. Verision => version

2023-02-01 08:08 UTC, JeevakaPrabu commented on bsp_diff/common/kernel/lts2020-yocto/0043-Bluetooth-btintel-Fix-bdaddress-comparison-with-garb.patch
> +bootloader mode and hence bd address in TLV structure needs to be validated
limit the number of characters/line to 72 characters

2023-02-06 15:59 UTC, JeevakaPrabu approved these changes

2023-02-07 09:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/283

2023-02-07 09:45 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/284

2023-02-07 10:01 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/286

2023-02-07 10:27 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/281

Done by "Kothapeta, BikshapathiX" <bikshapathix.kothapeta@intel.com>

2023-02-07 10:57 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/287

2023-02-07 11:58 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/290

2023-02-07 14:36 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/291

2023-02-07 14:39 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/292

2023-02-08 04:19 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/293

2023-02-08 06:16 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_sriov) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/294

2023-02-08 06:47 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/296

2023-02-08 14:47 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/celadon_smr0_stable-preintegration/builds/299

2023-02-08 18:29 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_stable-premerge/builds/174

Done by "Suresh, Prashanth" <prashanth.suresh@intel.com>

2023-02-08 21:04 UTC, merged

2023-02-08 21:05 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Suresh, Prashanth" <prashanth.suresh@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_stable-mergerequest/builds/134