Update the host patches for qemu 7.2.3
projectceladon/vendor-intel-utils pull request #1917
Opened 2023-06-13 05:27 UTC by yhe39

The 0001 revert the commit 0f957c53c84d655f2e99677d407cf2bbe1832de4 It exit(1) if audio backend failed to be found or initialized. The 0002 revert the commit 5890258aeeba303704ec1adca415e46067800777 It remove the remove the slirp submodule, since QEMU 7.1 don't support Ubuntu 18.04 anymore.

Tracked-On: OAM-110647

2023-06-15 06:48 UTC, feijiang1 reviewed
"It remove the remove" need duplicated "the remove" in description.
And please mention other patches are porting from qemu 7.0 patches.

2023-06-15 06:55 UTC, feijiang1 approved these changes

2023-06-15 14:46 UTC, JeevakaPrabu requested changes
- Please add why we are reverting this 3 patches in detailed commit message 
- generate the patches with git format-patch --no-numbered -12 to avoid 1/12..10/12

2023-06-16 02:11 UTC, JeevakaPrabu approved these changes

2023-06-16 07:36 UTC, YadongQi approved these changes

2023-06-16 07:40 UTC, swaroopbalan approved these changes

2023-06-16 12:47 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5159

Done by "Qi, Yadong" <yadong.qi@intel.com>

2023-06-16 13:32 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2989

Done by "Qi, Yadong" <yadong.qi@intel.com>

2023-06-16 19:33 UTC, merged

2023-06-16 19:33 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Qi, Yadong" <yadong.qi@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/3359