Save app setting of "Peak Performance" to database immediately.
projectceladon/vendor-intel-utils pull request #1923
Opened 2023-06-15 03:13 UTC by XuBing0

From the code, save to database only when system shutdown, data will not be saved if the system reboot or shutdown unexpectly, so we save the data when it is changed.

Tracked-On: OAM-108706

2023-06-15 03:14 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-06-15 03:33 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-06-15 08:47 UTC, dyang23 approved these changes
LGTM

2023-06-15 15:00 UTC, JeevakaPrabu requested changes
please use spaces instead of tabs.

2023-06-15 15:00 UTC, JeevakaPrabu commented on aosp_diff/celadon_ivi/packages/services/Car/0008-Save-app-setting-of-Peak-Performance-to-database-imm.patch
> ++	mWatchdogPerfHandler.writeToDatabase();
- Please use spaces instead of tabs.

2023-06-15 15:04 UTC, JeevakaPrabu requested changes
commit message recommendation with typo corrected. 

Save app setting of "Peak Performance" to database immediately.

As per the code, save to database is done only on system shutdown
and not on system reboot or unexpected shutdown.

Fix the issue by saving the data immediately upon change.

Tracked-On: OAM-108706
Signed-off-by: Bing Xu <bing.xu@intel.com>

2023-06-16 06:35 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-06-16 06:55 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-06-16 08:34 UTC, JeevakaPrabu approved these changes

2023-06-16 08:34 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-06-16 08:56 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-06-16 15:26 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/207

Done by "Xu, Bing" <bing.xu@intel.com>

2023-06-16 16:08 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/121

Done by "Xu, Bing" <bing.xu@intel.com>

2023-06-16 19:22 UTC, merged

2023-06-16 19:23 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Xu, Bing" <bing.xu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/128