[WIP] Resampler
projectceladon/vendor-intel-utils pull request #1990
Opened 2023-07-14 06:37 UTC by haochuan1982

2023-07-14 06:38 UTC, sysopenci commented
Expected syntax:
    Commit message one-line summary

      Extra paragraphs can be added here.

      Longer description that explains the problem / solution
      or whatever that needs to be said

      It can contain
        multiple lines
        multiple paragraphs
        blank lines
        references

      But each paragraph must be followed by a blank line

      However, you need to keep the 'Tracked-On', 'Change-Id',
      'Signed-off-by', ..., fields in the **lastest** paragraph of
      the commit message.

      Change-Id: I9e58f79c7faf7f0edb9792e8b5322ab161331141
      Tracked-On: https://jira.server.ext/browse/PROJECTA-123
      Signed-off-by: Developer Name <developer.name@intel.com>

2023-07-14 06:38 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-14 08:55 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-17 06:17 UTC, libinyang commented on aosp_diff/celadon_ivi/frameworks/av/media/libaudioprocessing/0004-AudioMixer-resampler-for-multi-channel-output.patch
> ++                uint32_t inChannelCount = getOutputChannelCount();
outChannelCount?

2023-07-17 15:11 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-17 17:25 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-18 00:35 UTC, xinxin-wan commented
LGTM

2023-07-24 05:46 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-24 08:01 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-25 14:53 UTC, gkdeepa approved these changes
LGTM

2023-07-25 17:01 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-26 07:59 UTC, JeevakaPrabu requested changes

2023-07-26 07:59 UTC, JeevakaPrabu commented on aosp_diff/celadon_ivi/frameworks/av/media/libaudioprocessing/0004-AudioMixer-resampler-for-multi-channel-output.patch
> ++                /* Martin, Chen: this is maybe android native bug.
Please remove "Martin, Chen: "

2023-07-26 07:59 UTC, JeevakaPrabu commented on aosp_diff/celadon_ivi/frameworks/av/media/libaudioprocessing/0004-AudioMixer-resampler-for-multi-channel-output.patch
> ++                /* Martin, Chen: this is maybe android native bug.
Detailed commit message should have details about the issue and fix

2023-07-26 13:25 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-26 14:12 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-26 14:43 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-26 14:56 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-26 15:04 UTC, JeevakaPrabu approved these changes

2023-07-26 15:20 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r1 (celadon_ivi), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_dev) - extra, build-cels - r2 (r2_caas_sriov), build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/379

2023-07-26 15:33 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-26 16:20 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-27 01:22 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-27 01:23 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/381

2023-07-27 03:29 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-27 04:30 UTC, JeevakaPrabu approved these changes

2023-07-27 08:46 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/383

Done by "Chen, Haochuan Z" <haochuan.z.chen@intel.com>

2023-07-27 09:19 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/252

Done by "Chen, Haochuan Z" <haochuan.z.chen@intel.com>

2023-07-27 13:59 UTC, merged

2023-07-27 14:00 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cactusi@intel.com 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/219