bionic: memmove optimization
projectceladon/vendor-intel-utils pull request #1994
Opened 2023-07-14 12:46 UTC by kaushlen

2023-07-14 12:47 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-14 15:01 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-20 07:58 UTC, shyjumon-n requested changes
Please maintain the original commit information in the commit msg, both in patch and main commit.

2023-07-20 08:39 UTC, JeevakaPrabu approved these changes

2023-07-20 08:45 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:cancelled Generate multi manifest original json

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/347

2023-07-20 17:30 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (caas), build-cels - r1 (caas_sriov), build-cels - r1 (celadon_ivi), build-cels - r2 (r2_caas), build-cels - r2 (r2_caas_dev) - extra, build-cels - r2 (r2_caas_sriov), build-cels - r2 (r2_celadon_ivi)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/348

2023-07-21 07:24 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/349

Done by "Kumar, Kaushlendra" <kaushlendra.kumar@intel.com>

2023-07-21 09:07 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/222

Done by "Kumar, Kaushlendra" <kaushlendra.kumar@intel.com>

2023-07-21 12:53 UTC, merged