Fix CTS not able to run to completion
projectceladon/vendor-intel-utils pull request #2011
Opened 2023-07-24 14:38 UTC by rairatne

* Disable operation causing CTS/VTS crashed
* Added validation check for zero and invalid dimensions
* Set all supported operations default to false
* Adds load model for all execute specs
* Add checks for ouput recived from remote infer
* Return INVALID_ARGUMENT for failures in setting PoolInfos

Tracked-On: OAM-111360

2023-07-24 14:39 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-24 14:39 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-24 15:10 UTC, JeevakaPrabu requested changes
Add Change-Id: for all newly added commits

2023-07-24 15:10 UTC, JeevakaPrabu commented on bsp_diff/cic_cloud/vendor/intel/external/project-celadon/nn-hal/0002-Fix-crashes-observed-during-VTS-execution.patch
> ++            if ( copied == 0 ) {
no need for extra space after ( and before )

2023-07-24 15:10 UTC, JeevakaPrabu commented on bsp_diff/cic_cloud/vendor/intel/external/project-celadon/nn-hal/0002-Fix-crashes-observed-during-VTS-execution.patch
> ++            } else if ( copied != expectedLength ) {
same comment as previous one

2023-07-24 15:10 UTC, JeevakaPrabu commented on bsp_diff/cic_cloud/vendor/intel/external/project-celadon/nn-hal/0002-Fix-crashes-observed-during-VTS-execution.patch
> ++                for ( const auto& dim : opDims ) { dims.push_back(dim); }
same comments as previous one

2023-07-24 15:49 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-24 15:49 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-24 17:12 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-24 17:12 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-24 17:26 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-24 17:26 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-25 04:15 UTC, akodanka approved these changes
LGTM

2023-07-25 07:47 UTC, JeevakaPrabu approved these changes

2023-07-25 11:00 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/1066

2023-07-25 16:33 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/android_cloud-premerge/builds/554

Done by "Kodankandath, Anoob Anto" <anoob.anto.kodankandath@intel.com>

2023-07-25 18:10 UTC, merged

2023-07-25 18:10 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Kodankandath, Anoob Anto" <anoob.anto.kodankandath@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/android_cloud-mergerequest/builds/570