Disabled operations causing VTS failures
projectceladon/vendor-intel-utils pull request #2012
Opened 2023-07-24 17:56 UTC by rairatne

Tracked-On: OAM-111364

2023-07-24 17:58 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-24 20:16 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-25 04:13 UTC, akodanka requested changes
Can you remove the existing patch file "0001-WA-Disabled-operations-causing-VTS-failures.patch" as part of this commit.

2023-07-25 04:13 UTC, akodanka commented on bsp_diff/common/vendor/intel/external/project-celadon/nn-hal/0001-Disabled-operations-causing-VTS-failures.patch
> ++        // case OperationType::UNIDIRECTIONAL_SEQUENCE_RNN:
There seems to be 2 copies of the unidir_seq_rnn.

2023-07-25 06:51 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-25 07:42 UTC, akodanka approved these changes

2023-07-25 07:46 UTC, JeevakaPrabu approved these changes

2023-07-25 12:30 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/5194

Done by "Kodankandath, Anoob Anto" <anoob.anto.kodankandath@intel.com>

2023-07-25 13:18 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/3019

Done by "Kodankandath, Anoob Anto" <anoob.anto.kodankandath@intel.com>

2023-07-25 15:28 UTC, merged

2023-07-25 15:29 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Kodankandath, Anoob Anto" <anoob.anto.kodankandath@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/3378