no need to exec the wait_for_keymaster
projectceladon/vendor-intel-utils pull request #2021
Opened 2023-07-28 03:59 UTC by syan10

2023-07-28 04:00 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2023-07-28 04:00 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-28 04:02 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-28 04:13 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-07-28 06:22 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-07-31 04:13 UTC, JeevakaPrabu requested changes
- Can this change done in base project itself instead of maintained as diff patch?
- Detailed commit message missing the issue, root cause and fix. Please follow the commit message format

2023-07-31 05:44 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-07-31 05:45 UTC, syan10 commented
> * Can this change done in base project itself instead of maintained as diff patch?
> * Detailed commit message missing the issue, root cause and fix. Please follow the commit message format

Jeevaka, 
this patch is for celadon-ivi project, since it has the boot time consideration, so we can remove this process to reduce the boot time. For android T later, google already have a patch in vold to remove the related codes of wait_for_keymaster.

2023-07-31 08:56 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-03 14:34 UTC, lchen43 approved these changes
LGTM

2023-08-04 08:14 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/409

Done by "Yan, Shaopu" <shaopu.yan@intel.com>

2023-08-04 08:44 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE: Trigger blocking tests Triggered: CIT-CIV-TGL-R(tgl_nuc:caas - userdebug), CIT-CIV-TGL-R(tgl_nuc:r2_caas - userdebug)

More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/272

2023-08-04 13:36 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/277

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-08-06 09:03 UTC, merged

2023-08-06 09:03 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/243