Fixing the lunch conflcit issue due to wrong index
projectceladon/vendor-intel-utils pull request #2048
Opened 2023-08-20 15:59 UTC by iViggyPrabhu

This patch is causing conflict in lunch. It is due to missing blob mentioned in index line of the diff patch and hence not being able to generate fake-ancestor. To fix the same, the patch has to be recreated.

2023-08-20 16:00 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2023-08-20 16:00 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-20 16:04 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2023-08-20 16:04 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-20 16:05 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2023-08-20 16:06 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-20 16:09 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-20 16:13 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-20 16:36 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-20 17:40 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-20 18:20 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-20 18:50 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-20 18:51 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-20 18:52 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-20 20:37 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-20 20:55 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-20 21:05 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-08-21 03:26 UTC, swaroopbalan approved these changes

2023-08-21 03:27 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/476

2023-08-21 03:49 UTC, JeevakaPrabu approved these changes

2023-08-21 04:59 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_celadon_ivi) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/477

2023-08-21 05:36 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-21 07:43 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-21 07:56 UTC, JeevakaPrabu requested changes
Commit message not in line with the file removal

2023-08-21 08:04 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-21 08:05 UTC, JeevakaPrabu approved these changes

2023-08-21 09:56 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-cels - r1 (celadon_ivi), build-cels - r2 (r2_celadon_ivi) - extra

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/479

2023-08-21 10:10 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-21 10:55 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-21 12:14 UTC, JeevakaPrabu approved these changes

2023-08-21 12:20 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-08-21 13:03 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-21 14:30 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-08-21 18:35 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/480

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-08-21 18:35 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/313

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-08-21 21:38 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/481

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-08-21 21:39 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/314

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-08-21 21:46 UTC, merged

2023-08-21 21:47 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/292