[WA] Add a revert patch to fix a perfetto issue
projectceladon/vendor-intel-utils pull request #2088
Opened 2023-09-14 08:16 UTC by jiaxuan-guo

This commit adds a patch which revert 14bb1fb893db1d915c98fce24263c0f42c259579 to fix the Pefetto problem.

Tracked-On: OAM-112068

2023-09-14 08:18 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-14 10:19 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-09-14 11:17 UTC, JeevakaPrabu requested changes

2023-09-14 11:17 UTC, JeevakaPrabu commented on bsp_diff/common/kernel/linux-intel-lts2021/0001-WA-Revert-f2fs-Fix-f2fs_truncate_partial_nodes-ftrac.patch
> +This reverts commit 14bb1fb893db1d915c98fce24263c0f42c259579 to fix the Pefetto problem.
Pefetto => Perfetto

2023-09-15 08:46 UTC, jiaxuan-guo commented on bsp_diff/common/kernel/linux-intel-lts2021/0001-WA-Revert-f2fs-Fix-f2fs_truncate_partial_nodes-ftrac.patch
> +This reverts commit 14bb1fb893db1d915c98fce24263c0f42c259579 to fix the Pefetto problem.
Thanks, modified.

2023-09-15 08:48 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-15 09:09 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-09-18 01:47 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-18 03:54 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-09-18 07:50 UTC, shyjumon-n approved these changes
Workaround patch.
LGTM

2023-09-18 16:43 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/597

Done by "Guo, Jade" <jade.guo@intel.com>

2023-09-19 09:45 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/600

Done by "Guo, Jade" <jade.guo@intel.com>

2023-09-20 06:05 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/367

Done by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com>

2023-09-20 09:23 UTC, merged

2023-09-20 09:23 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "T Prabhu, Vignesh" <vignesh.t.prabhu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/361