Enable V4L2Loopback with fops event broadcast
projectceladon/vendor-intel-utils pull request #2089
Opened 2023-09-14 09:33 UTC by neofang7

Issues: No V4L2loopback driver and device node when system boots up. Additionally, Apps opens upstream V4L2loopback device node as an output device and reports invalid capture device errors.

RootCause: V4L2loopback device node should inform user-space level server to write streams from physical camera device to loopback device before loopback open completed. Otherwise, the loopback device node is not a capture device, but an output device, which causes device open error in user space application.

Fix Details: In v4l2loopback open and close function, add netlink to broadcast the events to user space server, block open/close ops until the server starts to write video streams.

Tracked-On: OAM-112223

2023-09-14 09:35 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-09-14 09:49 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-09-19 07:23 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/604

2023-09-19 07:26 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/606

2023-09-19 09:34 UTC, JeevakaPrabu requested changes
please add "Tests done:" to commit message. for eg:

Tests done:
- Verified boot to UI
- Verified loopback device /dev/video50 is created
-

2023-09-19 09:34 UTC, JeevakaPrabu commented on bsp_diff/celadon_ivi/kernel/linux-intel-lts2021/0003-Enable-v4l2loopback-as-part-of-ivi-image.patch
> +From 05dc9f76fc54dc4c594c5b239a171b02dae6dd80 Mon Sep 17 00:00:00 2001
this file is not needed

2023-09-19 09:34 UTC, JeevakaPrabu commented on bsp_diff/celadon_ivi/kernel/linux-intel-lts2021/0002-Introduce-v4l2loopback-implementation.patch
> +From: Neo Fang <neo.fang@intel.com>
please split this into 2 patch files. 1st patch file only upstream code. 2nd patch file our changes on top of upstream patch file.

Also generate the patch file using "git format-patch --no-numbered -n" where n is the number of patches that needs to be created and copied to utils folder

2023-09-21 08:31 UTC, shivasku82 reviewed
Need to move the changes under apollo specific with new structure this changes wont be picked

2024-01-29 03:08 UTC, closed without merging