ASB - Security Patch integration October 2023
projectceladon/vendor-intel-utils pull request #2134
Opened 2023-10-09 06:37 UTC by alavalas1

ASB - Security Patch integration October 2023

Integration security patches

Tests done: SI-BAT TCs are passed

Tracked-On: OAM-112563

2023-10-09 06:39 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-10-09 08:45 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-10-09 11:34 UTC, tanujtekriwal approved these changes
LGTM

2023-10-10 09:40 UTC, shyjumon-n approved these changes
Google security patch integration.
LGTM

2023-10-11 04:27 UTC, JeevakaPrabu requested changes
Instead of SI BAT TCs are passed list down few important tests

2023-10-11 04:41 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-10-11 04:57 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2023-10-11 05:43 UTC, JeevakaPrabu approved these changes

2023-10-11 07:23 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-aicr - android_cloud (cic_cloud) - extra

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/1083

2023-10-11 11:12 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds cancelled

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/1084

2023-10-11 12:31 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Trigger Builds Triggered: build-aicr - android_cloud (cic_cloud) - extra

More details, logs, and binaries: /absp/builders/android_cloud-preintegration/builds/1085

2023-10-12 17:19 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/android_cloud-premerge/builds/570

Done by cdsart <cdsart@intel.com>

2023-10-12 18:21 UTC, merged

2023-10-12 18:21 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by cdsart <cdsart@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/android_cloud-mergerequest/builds/581