drm-i915-Sysfs-interface-to-get-GFX-shmem-usage
projectceladon/vendor-intel-utils pull request #2216
Opened 2023-11-17 06:59 UTC by ShenghuaLinINTEL

There is a requirement of a new interface for achieving below functionalities:

Need to provide Client based detailed information about the distribution of Graphics memory
Need to provide an interface which can provide info about the sharing of Graphics buffers between the clients.
The client based interface would also aid in debugging of memory usage/consumption by each client & debug memleak related issues.

With this new interface,

In case of memleak scenarios, we can easily zero in on the culprit client which is unexpectedly holding on the Graphics buffers for an inordinate amount of time.
We can get an estimate of the instantaneous memory footprint of every Graphics client.
We can now trace all the processes sharing a particular Graphics buffer.
By means of this patch we try to provide a sysfs interface to achieve the mentioned functionalities.

There are two files created in sysfs:
'i915_gem_meminfo' will provide summary of the graphics resources used by each graphics client.
'i915_gem_objinfo' will provide detailed view of each object created by individual clients.

Rebased for kernel v4.19 1A (Fan Yugang)

Removes unuseful shmem_inode_info->info_lock per Jeremy's optimization. Removes unuseful object info for each pid for performance optimization. Adds CONFIG_DRM_I915_MEMTRACK which depends on
CONFIG_DRM_I915_CAPTURE_ERROR to pass kernel config test.

Rebased for kernel v5.4 (He, Yue) (Wan, Shuang)

Rebased for kernel v5.10 and v5.15 (He, Yue)

Tracked-On: OAM-99250
Change-Id: Ib89cd2eaf6e1fc61311b43ebe54dbdc78554821b
Signed-off-by: Sourab Gupta sourab.gupta@intel.com
Sgined-off-by: Deepak S deepak.s@intel.com
Signed-off-by: Hu Beiyuan beiyuan.hu@intel.com
Signed-off-by: Mingwei Wang mingwei.wang@intel.com
Signed-off-by: Harish Krupo harish.krupo.kps@intel.com
Signed-off-by: Jeremy Compostella jeremy.compostella@intel.com
Signed-off-by: Yugang Fan yugang.fan@intel.com

2023-11-22 12:03 UTC, JeevakaPrabu requested changes
instead of "xdrm-i915-Sysfs-interface-to-get-GFX-shmem-usage" can we use "drm/i915: Sysfs interface to get GFX shmem usage"

2023-11-23 01:50 UTC, ShenghuaLinINTEL commented
@JeevakaPrabu  sure, I fixed that.

2023-11-23 06:23 UTC, JeevakaPrabu approved these changes

2023-11-23 06:58 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1057

2023-11-23 10:35 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1058

Done by "Lin, Shenghua" <shenghua.lin@intel.com>

2023-11-27 01:43 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1073

2023-11-28 03:54 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1090

Done by "Lin, Shenghua" <shenghua.lin@intel.com>

2023-11-28 03:54 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/588

Done by "Lin, Shenghua" <shenghua.lin@intel.com>

2023-11-28 08:19 UTC, merged

2023-11-28 08:19 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Lin, Shenghua" <shenghua.lin@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/607