[PATCH 1/2] Add AppOverrideSettings to hack app layout behavious
projectceladon/vendor-intel-utils pull request #2278
Opened 2023-12-26 09:13 UTC by gaohuadong

Now we support forceFullscreen and forceLandscape flag by per app setting. The settings is set by Andnroid prop as debug.app.override_settings= "<appName1>=<flags1>, <appName1>=<flags1>,..."
flags is a bitset for override features, bit0 is forceFullscreen and bit1 is forceLandscape. Other bits are not defined.

2024-01-04 07:42 UTC, bing8deng approved these changes

2024-01-04 07:59 UTC, gaohuadong commented
fixed for jira: OAM-113267 OAM-113201

2024-01-05 02:28 UTC, xmao4-intel approved these changes

2024-01-05 02:41 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1379

2024-01-05 03:24 UTC, qshi5 approved these changes

2024-01-05 04:06 UTC, shyjumon-n requested changes
PR commit msg need to follow the format template.
Please follow the commit message format:
 
<short summary>
<blank line>
<Issue detailed>
<blank line>
<fix detailed>
<blank line>

<Tests done: Detailed tests description done by developer>
 
Tracked-On:
Signed-off-by:
 
Note: Each line should be less than 72 characters


Also is this change for any particular customer request and i am not finding the JIRA ID also in the commit msg to check the exact scenario.

2024-01-05 04:06 UTC, shyjumon-n commented on aosp_diff/preliminary/frameworks/base/0001-Add-AppOverrideSettings-to-hack-app-layout-behavious.patch
> +Subject: [PATCH 1/2] Add AppOverrideSettings to hack app layout behavious
Please call out this as workaround and tag it with "[WA]".

2024-01-05 05:01 UTC, hongcheng-xie commented on aosp_diff/preliminary/frameworks/base/0001-Add-AppOverrideSettings-to-hack-app-layout-behavious.patch
> ++        String builtin = ",com.leting=3,com.cennavi.swearth=1";
Suggest don't hardcode workaround apps name in the code, set builtin string as empty here, instead we can set the workaround apps name by prop(debug.app.override_settings=xxx) under device config.

2024-01-05 07:37 UTC, hongcheng-xie approved these changes

2024-01-05 09:15 UTC, gaohuadong commented
Tests done on my NUC with base_aaos image

2024-01-05 09:21 UTC, shyjumon-n requested changes
Please work on the comments suggested in chat. Also this change cannot be put on common.

2024-01-05 13:52 UTC, shyjumon-n requested changes
Please modify the commit msg something like below:

[WA] Add AppOverrideSettings to hack app layout behavious
Support forceFullscreen and forceLandscape flag by per app
setting. 
The settings is set by Andnroid prop as
debug.app.override_settings="<appName1>=<flags1>,
<appName2>=<flags1>,...". Flags is a bitset for override features,
bit0 is forceFullscreen and bit1 is forceLandscape.
Other bits are not defined.
Tests done : Set the property and checked the App for 
             both full screen and landscape modes.
 
Tracked-On: OAM-113267
Signed-off-by: Marc Mao <marc.mao@intel.com>
Signed-off-by: Gao, HuadongX <huadongx.gao@intel.com>

2024-01-09 05:15 UTC, bing8deng approved these changes

2024-01-09 07:56 UTC, shyjumon-n approved these changes
LGTM

2024-01-09 08:49 UTC, hongcheng-xie approved these changes

2024-01-09 08:52 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1404

2024-01-09 09:00 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1405

2024-01-09 12:19 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:Update Bugs And Epics Update Bugs And Epics

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1406

2024-01-11 07:07 UTC, hongcheng-xie approved these changes

2024-01-11 10:13 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder

Your build ended in WARNING state. Please promote it carefully



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1421

Done by "Gao, HuadongX" <huadongx.gao@intel.com>

2024-01-12 05:15 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1423

Done by "Gao, HuadongX" <huadongx.gao@intel.com>

2024-01-12 05:15 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/761

Done by "Gao, HuadongX" <huadongx.gao@intel.com>

2024-01-12 07:04 UTC, merged

2024-01-12 07:05 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Gao, HuadongX" <huadongx.gao@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/782