Fix null pointer dereference coverity
projectceladon/vendor-intel-utils pull request #2302
Opened 2024-01-22 12:02 UTC by gowthambabu92

CID 200863: (#1 of 1): Dereference null return value (NULL_RETURNS)

Do null check before accessing the network interfaces.

Tracked-On: OAM-110042
Signed-off-by: Gowtham Anandha Babu <gowtham.anandha.babu@intel.com>

2024-01-22 12:04 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-01-22 12:21 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2024-01-22 12:37 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-01-22 12:37 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-01-22 12:51 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2024-01-22 12:53 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details

2024-01-22 13:16 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-01-22 16:32 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2024-01-23 07:53 UTC, JeevakaPrabu requested changes
Location of the file is not correct. Patch file has to be present under aosp_diff/base_aaos/<project_folder_path>/<patch file>

2024-01-24 08:55 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-01-24 10:51 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2024-01-24 16:01 UTC, bpanda24 approved these changes

2024-01-30 07:17 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1489

2024-01-30 07:26 UTC, balajim001 approved these changes
LGTM

2024-01-30 07:28 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1490

2024-01-30 07:51 UTC, JeevakaPrabu approved these changes

2024-01-30 10:18 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/1491

Done by "Babu, Gowtham Anandha" <gowtham.anandha.babu@intel.com>

2024-01-30 10:19 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/805

Done by "Babu, Gowtham Anandha" <gowtham.anandha.babu@intel.com>

2024-01-30 12:20 UTC, merged

2024-01-30 12:21 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Babu, Gowtham Anandha" <gowtham.anandha.babu@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/826