Add display adjustment UI on settings and API on framework
projectceladon/vendor-intel-utils pull request #2373
Opened 2024-03-11 07:23 UTC by XuBing0

Add UI on Settings and API on framework for display adjustment, including Saturation, Hue, Contrast, Luminance and White Balance.

Tracked-On: OAM-114024

2024-03-14 01:18 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-03-14 03:31 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-03-18 05:08 UTC, feijiang1 approved these changes
LGTM

2024-03-19 08:42 UTC, JeevakaPrabu requested changes
- Add Tests done to the PR
- Commit summary should be single line and <= 72 characters
- Detailed commit message should be <= 72 characters.

2024-03-19 10:01 UTC, shyjumon-n approved these changes
LGTM

2024-03-20 00:54 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-03-20 02:49 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-03-20 02:50 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-03-20 02:56 UTC, JeevakaPrabu approved these changes

2024-03-20 04:43 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-03-21 14:16 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-03-21 18:13 UTC, merged

2024-03-21 18:31 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_smr0_apollo-merge/66