Avoid the callback handler to be blocked of pm.installer which used to reconnect installd
projectceladon/vendor-intel-utils pull request #2401
Opened 2024-03-27 10:55 UTC by Kunkka1988

Use a private Thread to instead of the common BackgroundThread in pm.installer, to prevent the callback handler not to be blocked by the other tasks.

Pm.installer will try to reconnect installd if necessary, but sometimes the reconnection function cannot be performed due to the callback thread, as well as BackgroundThread becomes busy.

In the corner case, audioserver and audiopolicyservice might be crashed due to the same reason in stability testing.

Tracked-On: OAM-116189

2024-03-28 05:27 UTC, hongcheng-xie approved these changes

2024-03-28 07:17 UTC, xinxin-wan approved these changes

2024-03-29 07:14 UTC, dyang23 approved these changes
LGTM @xinxin-wan  @haochuan1982

2024-04-01 02:53 UTC, ankithbti52509 approved these changes
LGTM

2024-04-01 04:37 UTC, shyjumon-n requested changes
Please check commit heading, looks like truncated to me. Please make sure the message is within 72 chars.

2024-04-01 05:20 UTC, Kunkka1988 commented
> Please check commit heading, looks like truncated to me. Please make sure the message is within 72 chars.

Hi Shyjumon, I've updated the commit heading and make sure they are limited within 72 chars.
Please help to review it, thanks :)

2024-04-07 05:40 UTC, shyjumon-n approved these changes
LGTM

2024-04-07 05:54 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-04-07 07:11 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-04-07 07:55 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-04-08 03:07 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-04-08 03:10 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-04-08 03:15 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-04-08 03:45 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-04-08 03:58 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-08 05:58 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-08 06:34 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-08 11:11 UTC, merged

2024-04-08 11:28 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_smr0_apollo-merge/98