Enable mediasdk sw-codec for cvmb
projectceladon/vendor-intel-utils pull request #2428
Opened 2024-04-11 10:10 UTC by harvan

Tracked-On: OAM-116715

2024-04-11 10:13 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 10:36 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 14:40 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-11 17:32 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 07:59 UTC, shyjumon-n requested changes
Please check the comments and avoid #if 0.

Also commit msg should follow std template shared to you in IM

2024-04-15 07:59 UTC, shyjumon-n commented on aosp_diff/caas_cvmb/frameworks/av/0002-Resolve-the-issue-of-OMX.Intel.sw_vd.h264-5-not-bein.patch
> ++#if 0
Instead of #if 0

Shall we define some thing like 
#define TARGET_CHECK_TV 0

and use that 

#if TARGET_CHECK_TV

2024-04-15 07:59 UTC, shyjumon-n commented on aosp_diff/caas_cvmb/frameworks/av/0002-Resolve-the-issue-of-OMX.Intel.sw_vd.h264-5-not-bein.patch
> ++#if 0
Instead of #if 0

Shall we define some thing like
#define TARGET_CHECK_TV 0

and use that

#if TARGET_CHECK_TV

2024-04-15 07:59 UTC, shyjumon-n commented on aosp_diff/caas_cvmb/frameworks/av/0002-Resolve-the-issue-of-OMX.Intel.sw_vd.h264-5-not-bein.patch
> ++#if 0
Instead of #if 0

Shall we define some thing like
#define T_API_LEVEL_CHECK 0


and use that

#if T_API_LEVEL_CHECK

2024-04-15 07:59 UTC, shyjumon-n commented on bsp_diff/caas_cvmb/vendor/intel/libstagefrighthw/0001-Disable-hw-codec-property-check.patch
> ++#if 0
#if 0
replace with meaningful #define as suggested in above cases.

2024-04-15 08:02 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 10:10 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 10:26 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 10:30 UTC, harvan commented
Replace "#if 0" with macro "OMX_FILTER_VIDEO_CODEC" and "DISABLE_SW_CODEC".
Modify the commit msg with shared through IM.

2024-04-15 10:35 UTC, shyjumon-n approved these changes
LGTM

2024-04-15 12:25 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 14:31 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 16:01 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-15 16:31 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-16 20:49 UTC, merged

2024-04-16 21:08 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_tmr0_master-merge/80