Porting patches from Google
projectceladon/vendor-intel-utils pull request #2449
Opened 2024-04-25 07:12 UTC by soniravi31

Test: art/test/testrunner/testrunner.py --host --64 --optimizing -b
Tracked-On: OAM-117262

2024-04-25 07:21 UTC, vinaykompella requested changes
Please change the subject to AOSP. Add test information, and other details as per the guideline. Also include a couple of lines on what the issue was.

2024-04-25 14:30 UTC, vinaykompella approved these changes
LGTM

2024-04-29 09:41 UTC, shyjumon-n approved these changes
LGTM

2024-04-29 09:56 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-29 12:07 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-30 04:41 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-30 06:26 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-30 12:46 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-30 17:22 UTC, merged

2024-04-30 17:43 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/446