Enable AX210 and AX201 Bluetooth for Android Automotive
projectceladon/vendor-intel-utils pull request #2454
Opened 2024-04-28 03:04 UTC by zhaoye1

The BT chip is loaded as USB interface as hci0, the UsbHostManager
    is taking control of hci0 interface and doing initialization.
    Because of which Bluetooth-HAL is not able to send HCI cmds via
    hci0 interface, causing the hci_timeout_abort() crash.
    So BT is not enabled.

    Add BT chip vendor id and product id in config deny list, so that
    UsbHostManager skips the USB interface intialization for hci0.

    Tests:
    Open bluetooth in Settings app,
    bluetooth device can be found.

    Tracked-On:OAM-118006

2024-04-28 03:06 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-04-28 03:07 UTC, dyang23 approved these changes
LGTM

2024-04-28 03:09 UTC, qshi5 requested changes
Must we modify AOSP for feature enabling? If yes, we need to evaluate the impact after changing GSI.

2024-04-28 03:48 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-04-28 03:51 UTC, sysopenci commented
Improper Commit Message
Tracked on not found in commit message,
    make sure Tracked-On: Jira-ticket  is present.

2024-04-28 08:01 UTC, qshi5 approved these changes

2024-04-28 08:30 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-28 10:23 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-28 13:55 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-28 15:51 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-29 01:17 UTC, zhy1030 approved these changes

2024-04-29 01:19 UTC, dyang23 approved these changes
LGTM

2024-04-29 02:57 UTC, lchen43 approved these changes
LGTM

2024-04-29 03:26 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-29 05:08 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-29 05:16 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-29 09:36 UTC, merged