Enable wifi RTT and NAN features
projectceladon/vendor-intel-utils pull request #2518
Opened 2024-06-27 07:59 UTC by gowthambabu92

RTT and NAN features are not enabled in caas.

Enabled RTT and NAN for caas. Since NAN and hotspot cannot work simultaneously, moved NAN to mixins options, whenever required can enable and validate.

Tests done:
[RTT]
1. Flash BM
2. In adb shell #>pm list features | grep wifi
3. Check rtt is listing
4. Verify RTT service is running in logcat
5. Check wifi on success
6. Check hotspot on success

[NAN]
1. Build with nan=true and flash BM
2. In adb shell #>pm list features | grep wifi
3. Check aware is listing
4. Verify aware service is running in logcat
5. Check wifi on success

Tracked-On: OAM-121432

2024-06-27 09:25 UTC, bpanda24 approved these changes

2024-06-27 11:11 UTC, balajim001 approved these changes
LGTM

2024-06-27 11:35 UTC, JeevakaPrabu requested changes
please split this into 2 commits. one clearly calling out the reason for removal of the diff patch and other one for RTT and NAN

2024-06-27 11:36 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-27 13:02 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-27 13:45 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-27 16:37 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-27 16:39 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-27 18:37 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-27 18:37 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-27 22:46 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-28 03:19 UTC, merged

2024-06-28 03:35 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/601