Avoid HIGH_ACCURACY request from stationary throttling
projectceladon/vendor-intel-utils pull request #2534
Opened 2024-07-11 10:39 UTC by AlamIntel

Bug: 319054085

Test: atest StationThrottlingLocationProviderTest
Change-Id: I33e945b62c660db7e0ecce45ca6959213cd64bf4

Tracked-On: OAM-122204

2024-07-12 06:40 UTC, tanujtekriwal approved these changes
LGTM

2024-07-12 06:42 UTC, tanujtekriwal requested changes
wait

2024-07-12 10:48 UTC, tanujtekriwal approved these changes
LGTM

2024-07-12 11:57 UTC, shyjumon-n approved these changes
LGTM

2024-07-12 14:35 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-12 21:31 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-13 01:29 UTC, merged

2024-07-13 01:50 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/657