Fix metadata issue when reconnect pixel
projectceladon/vendor-intel-utils pull request #2726
Opened 2024-11-25 05:23 UTC by AmanBh0709

When reconnecting pixel some times metadata is not synced.

Issue: bt-stack issuing two AVRC browse channel, one as acceptor, other as initator, which is causing collision in lcid and resulting in l2cap disconnection of avrc browse channel, resulting in metadata sync issue.

Solution: Don't initiate avrc browse channel as initiator, open only as acceptor. Now browse channel is always success and metadata is seen everytime.

Tracked-On: OAM-127243

2024-11-25 05:33 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 12:14 UTC, gowthambabu92 requested changes

2024-11-25 12:14 UTC, gowthambabu92 commented on aosp_diff/base_aaos/packages/modules/Bluetooth/0001-Fix-metadata-issue-when-reconnect-pixel.patch
> ++      log::verbose("Not opening AVRC Browse channel");
Indentation issue, pls make sure all added lines are equally intended.

2024-11-25 12:14 UTC, gowthambabu92 commented on aosp_diff/base_aaos/packages/modules/Bluetooth/0001-Fix-metadata-issue-when-reconnect-pixel.patch
> ++      log::verbose("Not opening AVRC Browse channel");
Change the verbose logging as
"Not opening AVRC Browse channel as INT"

Please refer the exact logging we did in older patches.

2024-11-25 12:35 UTC, gowthambabu92 approved these changes
Looks good.

2024-11-25 12:36 UTC, gowthambabu92 requested changes
Pls update commit msg with Tests done: field.

2024-11-25 12:36 UTC, gowthambabu92 commented on aosp_diff/base_aaos/packages/modules/Bluetooth/0001-Fix-metadata-issue-when-reconnect-pixel.patch
> +
Tests done is missing.

2024-11-25 12:39 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 12:45 UTC, gowthambabu92 approved these changes
Looks good.

2024-11-25 12:50 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 12:52 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 12:53 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 13:01 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 14:14 UTC, balajim001 approved these changes
LGTM

2024-11-25 15:31 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 20:18 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-25 23:53 UTC, merged

2024-11-26 00:21 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/833