Fix for improper text alignment in bluetooth rename dialogbox
projectceladon/vendor-intel-utils pull request #2727
Opened 2024-11-25 06:06 UTC by AmanBh0709

The default font size for this dialog box is 32.0 which causes the text to become cropped.

Fixed by reducing the font size by 6.0 units to fit the Text field properly

Tracked-On: OAM-127240

2024-11-25 12:06 UTC, gowthambabu92 approved these changes
LGTM

2024-11-25 12:10 UTC, ankithbti52509 approved these changes
LGTM

2024-11-25 12:11 UTC, gowthambabu92 requested changes

2024-11-25 12:11 UTC, gowthambabu92 commented on aosp_diff/base_aaos/packages/apps/Car/Settings/0001-Fix-for-improper-text-alignment-in-bluetooth-rename-.patch
> ++            deviceNameView.setTextSize(textSize - 6);
6 -> Looks like a magic number,
We can define something like below
private static final int BLUETOOTH_RENAME_TEXT_OFFSET = 6;

2024-11-25 12:35 UTC, gowthambabu92 approved these changes
Looks good.

2024-11-25 14:13 UTC, balajim001 approved these changes
LGTM

2024-11-26 10:38 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-26 11:04 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-26 12:30 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-27 03:32 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-27 05:14 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-27 11:15 UTC, merged

2024-11-27 11:40 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/838