ASB JAN 2025 Security Patches integration
projectceladon/vendor-intel-utils pull request #2756
Opened 2024-12-16 08:15 UTC by AlamIntel

Integrating Google Android Security Bulletin Patches

Test done: STS r34 TCs Passed.

Tracked-On: OAM-128566

2025-01-03 04:59 UTC, tanujtekriwal approved these changes
LGTM

2025-01-06 09:57 UTC, shyjumon-n approved these changes
LGTM

2025-01-06 10:11 UTC, shyjumon-n requested changes
Check status of the STS issue mentioned offline

2025-01-09 12:50 UTC, sysopenci commented
This pull request cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2025-01-09 12:53 UTC, AlamIntel commented
The STS failure test "android.security.cts.VisualizerEffectTest#testVisualizer_MalformedConstructor" passed on below PR. 
and it got merged.
PR: https://github.com/projectceladon/device-androidia-mixins/pull/2215

Now STS 100% passing, for both BM and Base_aaos target.

2025-01-09 13:36 UTC, sysopenci commented
This pull request cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2025-01-10 10:03 UTC, closed without merging